AWSTemplateFormatVersion: 2010-09-09
Description: Example of whitelisting IAM resources to access a secret

Parameters:
  WhitelistedRoleIds:
    Type: CommaDelimitedList
    Description: >
      IDs (AROA*, or AIDA*) to whitelist access for on the created secret.
      Find the Role ID by running aws iam get-role --role-name ROLE-NAME.
      Remember to append :* to the end of the Role IDs.
      Find the User ID by running aws iam get-user --user-name USER-NAME.
      User IDs do not need :* appended to the end.

Resources:
  TopSecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: This is top secret
      SecretString: asdf
  SecretResourcePolicy:
      Type: 'AWS::SecretsManager::ResourcePolicy'
      Properties:
          SecretId: !Ref TopSecret
          ResourcePolicy:
            Version: 2012-10-17
            Statement:
              - Resource: !Ref TopSecret
                Action: 'secretsmanager:GetSecretValue'
                Effect: Deny
                Principal: '*'
                Condition:
                  StringNotLike:
                    aws:userId: !Ref WhitelistedRoleIds
