AWSTemplateFormatVersion: 2010-09-09
Description: Template for global DDB Table

Resources:
  Table:
    Type: AWS::DynamoDB::GlobalTable
    Properties: 
      Replicas:
        - Region: !Ref AWS::Region
      AttributeDefinitions: 
        -
          AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        -
          AttributeName: id
          KeyType: HASH

Outputs:
  TableName:
    Description: The created DDB table name
    Value: !Ref Table
    Export:
      Name: !Sub ${AWS::StackName}-ddb-table-name
